name: Windows Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: configure git line endings
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
      with:
        # Needed for commands that depend on git tags
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Setup Msys2 environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
    - name: Prepare mingw64 environment
      shell: msys2 {0}
      run: ./prepare_mingw64.sh
    - name: Build ffmpeg
      shell: msys2 {0}
      run: ./install_ffmpeg.sh
    - name: Build Livepeer
      shell: msys2 {0}
      run: ./ci_env.sh make livepeer livepeer_cli livepeer_bench livepeer_router
    - name: Import gpg key 
      shell: msys2 {0}
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      run: |
        echo "$GPG_PRIVATE_KEY" > ~/privatekey.asc
        gpg --pinentry-mode loopback --passphrase $GPG_PASSPHRASE --import ~/privatekey.asc
    - name: Upload build
      if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      shell: msys2 {0}
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
        GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
        GCLOUD_SECRET: ${{ secrets.GCLOUD_SECRET }}
        DISCORD_URL: ${{ secrets.DISCORD_URL }}
      run: ./upload_build.sh
